const matchData = {
  matchId: 'match1',
  venue: 'Infosys Ground',
  tournamentName: 'AJM Corporate Cricket League',
  format: 'T20',
  inn1: {
    batStats: {
      bat1: {
        name: 'Rohil Sharma',
        runs: 0,
        ballsPlayed: 0,
        fours: 0,
        sixes: 0,
        isOut: false,
        isStriker: false,
      },
      bat2: {
        name: 'Shubham Gill',
        runs: 0,
        ballsPlayed: 0,
        fours: 0,
        sixes: 0,
        isOut: false,
        isStriker: false,
      },
      bat3: {
        name: 'Ajinkya Rahane',
        runs: 0,
        ballsPlayed: 0,
        fours: 0,
        sixes: 0,
        isOut: false,
        isStriker: false,
      },
      bat4: {
        name: 'Cheteshwar Pujara',
        runs: 0,
        ballsPlayed: 0,
        fours: 0,
        sixes: 0,
        isOut: false,
        isStriker: false,
      },
    },
    bowlStats: {
      bowl1: {
        id: 'bowl1',
        name: 'Nathan Lyon',
        balls: 0,
        overs: 0,
        wickets: 0,
        maidens: 0,
        runsGiven: 0,
        wides: 0,
        nbs: 0,
        isCurrentBowler: false,
      },
      bowl2: {
        id: 'bowl2',
        name: 'Mitchell Starc',
        balls: 0,
        overs: 0,
        wickets: 0,
        maidens: 0,
        runsGiven: 0,
        wides: 0,
        nbs: 0,
        isCurrentBowler: false,
      },
      bowl3: {
        id: 'bowl3',
        name: 'Marcus Stoinis',
        balls: 0,
        overs: 0,
        wickets: 0,
        maidens: 0,
        runsGiven: 0,
        wides: 0,
        nbs: 0,
        isCurrentBowler: false,
      },
      bowl4: {
        id: 'bowl4',
        name: 'Josh Hazlewood',
        balls: 0,
        overs: 0,
        wickets: 0,
        maidens: 0,
        runsGiven: 0,
        wides: 0,
        nbs: 0,
        isCurrentBowler: false,
      },
    },
    currentStats: {
      striker: 'bat1',
      nonStriker: 'bat2',
      currentBowler: 'bowl1',
    },
    battingTeam: 'India',
    totalRuns: 0,
    totalWickets: 0,
    totalOvers: 0,
    totalExtras: 0,
  },
  inn2: {
    batStats: {
      bat1: {
        name: 'Rohil Sharma',
        runs: 0,
        ballsPlayed: 0,
        fours: 0,
        sixes: 0,
        isOut: false,
        isStriker: false,
      },
      bat2: {
        name: 'Shubham Gill',
        runs: 0,
        ballsPlayed: 0,
        fours: 0,
        sixes: 0,
        isOut: false,
        isStriker: false,
      },
      bat3: {
        name: 'Ajinkya Rahane',
        runs: 0,
        ballsPlayed: 0,
        fours: 0,
        sixes: 0,
        isOut: false,
        isStriker: false,
      },
      bat4: {
        name: 'Cheteshwar Pujara',
        runs: 0,
        ballsPlayed: 0,
        fours: 0,
        sixes: 0,
        isOut: false,
        isStriker: false,
      },
    },
    bowlStats: {
      bowl1: {
        id: 'bowl1',
        name: 'Nathan Lyon',
        balls: 0,
        overs: 0,
        wickets: 0,
        maidens: 0,
        runsGiven: 0,
        wides: 0,
        nbs: 0,
        isCurrentBowler: false,
      },
      bowl2: {
        id: 'bowl2',
        name: 'Mitchell Starc',
        balls: 0,
        overs: 0,
        wickets: 0,
        maidens: 0,
        runsGiven: 0,
        wides: 0,
        nbs: 0,
        isCurrentBowler: false,
      },
      bowl3: {
        id: 'bowl3',
        name: 'Marcus Stoinis',
        balls: 0,
        overs: 0,
        wickets: 0,
        maidens: 0,
        runsGiven: 0,
        wides: 0,
        nbs: 0,
        isCurrentBowler: false,
      },
      bowl4: {
        id: 'bowl4',
        name: 'Josh Hazlewood',
        balls: 0,
        overs: 0,
        wickets: 0,
        maidens: 0,
        runsGiven: 0,
        wides: 0,
        nbs: 0,
        isCurrentBowler: false,
      },
    },
    currentStats: {
      striker: 'bat1',
      nonStriker: 'bat2',
      currentBowler: 'bowl1',
    },
    battingTeam: 'Australia',
    target: 0,
    totalRuns: 0,
    totalWickets: 0,
    totalOvers: 0,
    totalExtras: 0,
  },
};

export default matchData;
