export const ADD_MATCH_DETAILS = "ADD_MATCH_DETAILS";
export const ADD_HOME_TEAM_PLAYER = "ADD_HOME_TEAM_PLAYER";
export const ADD_AWAY_TEAM_PLAYER = "ADD_AWAY_TEAM_PLAYER";
export const REMOVE_HOME_PLAYER = "REMOVE_HOME_PLAYER";
export const REMOVE_AWAY_PLAYER = "REMOVE_AWAY_PLAYER";
export const SET_BATTING_TEAM = "SET_BATTING_TEAM";
export const SET_INITIAL_STATS = "SET_INITIAL_STATS";
